name: CI/CD Deploy to Cloud

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Deploying via SSH to AWS Cloud
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          # 1. Sabse pehle poore folder ki permission 'ubuntu' user ko wapas dilayein (FETCH_HEAD fix)
          sudo chown -R $USER:$USER ${{ secrets.PROJECT_PATH }}
          
          # 2. Git ko automatic batayein ki yeh directory safe hai
          git config --global --add safe.directory ${{ secrets.PROJECT_PATH }}
          
          # 3. Project folder ke andar jayein
          cd ${{ secrets.PROJECT_PATH }}
          
          # 4. Git code pull karein (Ab permission issue nahi aayega)
          git pull origin main
          
          # 5. 💡 Sudo ke sath naya Docker Compose bina dash ke chalayein
          sudo docker compose up --build -d
          
          # 6. Sudo ke sath unused images ko clean karein
          sudo docker image prune -f
