name: CI/CD Deploy to Cloud

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Deploying via SSH to AWS Cloud
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          # 1. Poore folder ki permission user ko dilaao (Zaroori hai)
          sudo chown -R $USER:$USER ${{ secrets.PROJECT_PATH }}
          
          # 2. Git safe directory set karo
          git config --global --add safe.directory ${{ secrets.PROJECT_PATH }}
          
          # 3. Project folder ke andar jao
          cd ${{ secrets.PROJECT_PATH }}
          
          # 4. GitHub se sabse naya data fetch karo bina merge kiye
          git fetch origin main
          
          # 5. 🔥 Server par kiye gaye saare manual badlavo ko dho dalo aur GitHub wala code force apply karo
          git reset --hard origin/main
          
          # 6. 💡 Sudo ke sath Docker Compose bina dash ke chalayein
          sudo docker compose up --build -d
          
          # 7. Sudo ke sath faltu cache images clean karein
          sudo docker image prune -f
